version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - turing-network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    volumes:
      - minio_storage:/data
    command: server --address ":9099" --console-address ":9091" /data
    ports:
      - "9091:9091"
      - "9099:9099"
    networks:
      - turing-network

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - turing-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
    networks:
      - turing-network
      
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_DB}
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - turing-network

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    environment:
      - MQTT_ADMIN_USER=${MQTT_ADMIN_USER}
      - MQTT_ADMIN_PASSWORD=${MQTT_ADMIN_PASSWORD}
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config
    networks:
      - turing-network
    command: "mosquitto -c /mosquitto/config/mosquitto.conf"

volumes:
  postgres_data: {}
  minio_storage: {}
  redis_volume_data: {}
  influxdb_data: {}
  mosquitto_data: {}
  mosquitto_config: {}

networks:
  turing-network:
    external: true
